name: CI Release

on:
  push:
    branches:
      - master

jobs:
  release:
    strategy:
      matrix:
        go_version: [1.13.x,1.15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Generage changelog
        id: generate_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          addSections: '{"documentation":{"prefix":"### Documentation","labels":["documentation"]},"tests":{"prefix":"### Testing","labels":["tests"]}}'
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          stripGeneratorNotice: "true"
          onlyLastTag: false
          compareLink: true
          excludeTagsRegex: "v.*"
          verbose: true

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build binaries
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: go-enabler
          targets: linux/amd64,darwin/amd64,windows/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          ldflags: -s -w

      - name: Delete old release
        uses: jagger27/delete-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ci-build

      - name: Update ci-build tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ci-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ci-build
          release_name: CI Release
          draft: false
          prerelease: true
          body: ${{ steps.generate_changelog.outputs.changelog }}
          body_path: ./CHANGELOG.md

      - name: Push release binaries
        uses: glentiki/xbin-release-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          assets_path: ./build
